version: '2'
services:
    hbinszuulserver-app:
        image: hbinszuulserver
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://hbinszuulserver-mariadb:3306/hbinszuulserver
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8861:8861
    hbinszuulserver-mariadb:
        extends:
            file: mariadb.yml
            service: hbinszuulserver-mariadb
